import React from 'react';
import DashboardIcon from 'react-icons/lib/md/dashboard';
import VehiclesIcon from 'react-icons/lib/md/directions-car';
import ReportsIcon from 'react-icons/lib/md/format-list-bulleted';
import AlertsIcon from 'react-icons/lib/md/warning';
import AdminIcon from 'react-icons/lib/md/settings';
import AccountsIcon from 'react-icons/lib/md/supervisor-account';

export default {
  logo: require('./logo.png'),
  fontFamily: 'Roboto',
  fontSize: 14,
  fontWeight: 300,
  backgroundColor: 'white',
  tertiaryColor: '#aaa',
  tertiaryColorContrast: '#fff',
  quaternaryColor: '#DAEEF5',
  quaternaryColorContrast: '#333',
  textColor: '#333',
  primaryColor: '#1976D2',
  primaryColorContrast: 'white',
  primarypastelColor: '#E6F8FA',
  primarypastelColorContrast: '#51BCCF',
  primarylightColor: '#A7E5ED',
  primarylightColorContrast: 'white',
  primarydarkColor: '#5ACFDD',
  primarydarkColorContrast: 'white',
  secondaryColor: '#E1E1E4',
  secondaryColorContrast: '#00bdfb',
  secondarypastelColor: '#FFFFFF',
  secondarypastelColorContrast: '#00bdfb',
  secondarylightColor: '#FAFAFA',
  secondarylightColorContrast: '#00bdfb',
  secondarydarkColor: '#DBDBDB',
  secondarydarkColorContrast: '#00bdfb',
  alertColor: '#FFC734',
  alertColorContrast: '#886a0f',
  alertpastelColor: '#FFE6A4',
  alertpastelColorContrast: '#BE8804',
  alertlightColor: '#FFD158',
  alertlightColorContrast: '#BE8804',
  alertdarkColor: '#FBB600',
  alertdarkColorContrast: '#886a0f',
  dangerColor: '#F76063',
  dangerColorContrast: '#F9F2F4',
  dangerpastelColor: '#FCCBCC',
  dangerpastelColorContrast: '#D50107',
  dangerlightColor: '#F98284',
  dangerlightColorContrast: '#F9F2F4',
  dangerdarkColor: '#F42A2F',
  dangerdarkColorContrast: '#FFFFFF',
  defaultColor: '#F5F5F5',
  defaultColorContrast: '#868484',
  defaultpastelColor: '#FFFFFF',
  defaultpastelColorContrast: '#868484',
  defaultlightColor: '#FAFAFA',
  defaultlightColorContrast: '#868484',
  defaultdarkColor: '#DBDBDB',
  defaultdarkColorContrast: '#868484',
  infoColor: '#00bdfb',
  infoColorContrast: '#FDFEFD',
  infopastelColor: '#89e2ff',
  infopastelColorContrast: '#3c7b90',
  infolightColor: '#39ceff',
  infolightColorContrast: '#236f88',
  infodarkColor: '#0090bf',
  infodarkColorContrast: '#FFFFFF',
  successColor: '#56ad06',
  successColorContrast: 'white',
  successpastelColor: '#a3d675',
  successpastelColorContrast: '#497126',
  successlightColor: '#86c74a',
  successlightColorContrast: '#FFF',
  successdarkColor: '#3d8000',
  successdarkColorContrast: '#FFF',
  systemColor: '#4D577B',
  systemColorContrast: '#F9F2F4',
  systempastelColor: '#BBC0D4',
  systempastelColorContrast: '#515C84',
  systemlightColor: '#BBC0D4',
  systemlightColorContrast: '#515C84',
  systemdarkColor: '#383E59',
  systemdarkColorContrast: '#FFFFFF',
  warningColor: '#ff7b1e',
  warningColorContrast: '#FFF',
  warningpastelColor: '#ffbc8d',
  warningpastelColorContrast: '#b55a1a',
  warninglightColor: '#ff9b55',
  warninglightColorContrast: '#FFF',
  warningdarkColor: '#da5a00',
  warningdarkColorContrast: '#FFF',
  errorColor: '#cc0000',
  errorColorContrast: 'white',
  disabledColor: '#c0c0c0',
  disabledColorContrast: 'white',
  icons: {
    dashboard: (<DashboardIcon />),
    vehicles: (<VehiclesIcon />),
    reports: (<ReportsIcon />),
    alerts: (<AlertsIcon />),
    admin: (<AdminIcon />),
    accounts: (<AccountsIcon />),
  },
  sideMenuBackgroundColor: '#888',
  sideMenuTextColor: '#fff',
  sideMenuBorderColors: '#999',
  palette: {
    primary1Color: '#1976D2',
    primaryTextColor: '#FFFFFF',
  },
  textField: {
    focusColor: '#1976D2',
  },
};
