/* AUTH ACTIONS */
export const AUTH_STATE_CHANGED = "AUTH_STATE_CHANGED"
export const AUTH_STATE_BUSY = "AUTH_STATE_BUSY"

/* SIGNUP ACTIONS*/
export const INCOMPLETE_EMAIL = "INCOMPLETE_EMAIL"
export const INCOMPLET_PREFERENCE = "INCOMPLET_PREFERENCE"
export const EMAIL_FILLED = "EMAIL_FILLED"
export const TAB_CHANGE = "TAB_CHANGE"
export const USER_FORM_COMPLETE = "USER_FORM_COMPLETE"

/* TWO PERSON PLAN SUBSCRIPTION ACTIONS*/
export const LOAD_TWO_PERSON_PLAN_SUCCESS = "LOAD_TWO_PERSON_PLAN_SUCCESS"
export const SELECT_TWO_PERSON_SUBSCRIPTION = "SELECT_TWO_PERSON_SUBSCRIPTION"

/* FAMILY PLAN SUBSCRIPTION ACTIONS*/
export const LOAD_FAMILY_PLAN_SUCCESS = "LOAD_FAMILY_PLAN_SUCCESS"
export const SELECT_FAMILY_SUBSCRIPTION = "SELECT_FAMILY_SUBSCRIPTION"

/* SELECT PLAN ACTIONS */
export const SELECT_PLAN = "SELECT_PLAN"

/* PRODUCT ACTIONS */
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS"
export const LOAD_THIS_WEEK_TWO_PEOPLE_PRODUCT = "LOAD_THIS_WEEK_TWO_PEOPLE_PRODUCT"
export const LOAD_THIS_WEEK_FAMILY_PRODUCT = "LOAD_THIS_WEEK_FAMILY_PRODUCT"
export const SELECT_PRODUCT = "SELECT_PRODUCT"
export const UNSELECT_PRODUCT = "UNSELECT_PRODUCT"
export const CLEAR_PRODUCT_SLECTION = "CLEAR_PRODUCT_SLECTION"
export const CHANGE_PRODUCT_SELECTION_CONTEXT = "CHANGE_PRODUCT_SELECTION_CONTEXT"

/* ACCOUNTS ACTIONS */
export const SAVE_ADDRESS = "SAVE_ADDRESS"
export const ADDRESS_CHANGED = "ADDRESS_CHANGED"
export const LOADING_ADDRESS = "LOADING_ADDRESS"
export const ACCOUNT_CHANGED = "ACCOUNT_CHANGED"
export const CARDS_CHANGED = "CARDS_CHANGED"

/* DELIVERY ACTIONS */
export const SAVE_DELIVERY = "SAVE_DELIVERY"
export const GET_DELIVERY = "GET_DELIVERY"
export const SUBSCRIPTION_CHANGED = "SUBSCRIPTION_CHANGED"
